### ISSUE TITLE
Which URL is needed for showing the result

### ISSUE THREAD

**Issue by mjhcremer** [gitpod-samples/template-laravel#14]
I made a gitpod and it is starting, but when I want to see the result I get the message "Port 8000 Not Found".
Am I using the right URL?

**Comment by ijpatricio** [comment]
Did you start the server with `php artisan serve` ?

**Comment by mjhcremer** [comment]
Sorry my mistake.

**Comment by ijpatricio** [comment]
No problem, it happens to all of us 😄
