### ISSUE TITLE
Update Laravel

### ISSUE THREAD

**Issue by ijpatricio** [gitpod-samples/template-laravel#15]
Hey @axonasif  @Siddhant-K-code 

I think we should update the Laravel scene on Gitpod.

Now, sqlite is default, so maybe this repo would redirect to a new one: template-php-laravel or template-laravel?

Then, there's another aspect: Laravel embraces frontend, and there's at least three main ones: 
- Blade and Livewire
- Inertia/React
- Inertia/Vue

Is this something you would like to see reflected on starter templates, or the more simple just PHP?

Anyways, they all have JS, because of Tailwind compilation.

**Comment by axonasif** [comment]
Hi @ijpatricio!

Thanks for bringing this up 🙌

I'm not fully sure what you're suggesting. Are you suggesting to rename the repository?

**Comment by ijpatricio** [comment]
Hi @axonasif 

My pleasure!

Sorry I was confusing. I'll split it better, since I made a suggestion and a question 😅 

### 1) Suggestion:
- On the latest version, Laravel defaults to using sqlite, so we should stop using MySQL on the template.
- We should rename the template: `template-laravel`
- Only after the code modification

### 2) Question:
- Laravel has a few options when it comes to starter kits. Should we add more templates, to cover also `Laravel+Vue` and `Laravel+React` ?

**Comment by ijpatricio** [comment]
Oh, still on 1)

- Can I start the upgrade for the latest version then?

**Comment by axonasif** [comment]
@ijpatricio that would be very much appreciated 🙏

**Comment by ijpatricio** [comment]
Hey @axonasif , it's done in #16 
However, because there's a suggestion to rename the repo to be consistent with what's inside, there's still a TODO task to do in `README.md` which is to update te "Open in Gitpod" button link.

Let me know what you think.

**Comment by axonasif** [comment]
> However, because there's a suggestion to rename the repo to be consistent with what's inside, there's still a TODO task to do in README.md which is to update te "Open in Gitpod" button link.

That's the easy part, just let me know when you need that to be done 🙌

Thanks again!

**Comment by axonasif** [comment]
@ijpatricio should I do it now?

**Comment by ijpatricio** [comment]
@axonasif yes please, go ahead, I will update right after

**Comment by axonasif** [comment]
@ijpatricio done!

**Comment by ijpatricio** [comment]
@axonasif awesome, thank you!

I ended up adding a preview to the README, do you like it or should I remove?

![CleanShot 2024-10-31 at 17 32 55](https://github.com/user-attachments/assets/429eba8f-9f18-4fc0-9e51-58f8b04bb4d5)

**Comment by axonasif** [comment]
@ijpatricio i think an image like that is always nice and intriguing!

**Comment by axonasif** [comment]
Thanks a ton @ijpatricio for keeping this template up to date 🙌

**Comment by ijpatricio** [comment]
My pleasure @axonasif !
